### ISSUE TITLE
Exit is not working properly with Nimbus

### ISSUE THREAD

**Issue by dsimog01** [dappnode/StakingBrain#220]
Nimbus is returning errors when trying to exit a validator from the Staking Brain:

![image](https://user-images.githubusercontent.com/47595345/234331865-d27f7f02-3e99-4767-b076-efbef53049ed.png)

```
[ERROR] {
  "code": "ERR_HTTP",
  "errno": 404,
  "path": "/eth/v1/beacon/states/head/validators/0x...00",
  "syscall": "GET",
  "hostname": "beacon-validator.nimbus-prater.dappnode"
}
```

**Comment by pablomendezroyo** [comment]
there should be opened an issue in the upstream project nimbus
