### ISSUE TITLE
NavBar should be stuck to the top

### ISSUE THREAD

**Issue by dsimog01** [dappnode/StakingBrain#226]
NavBar should be shown in the top part of the page even if the user scrolls down

**Comment by pablomendezroyo** [comment]
I do not have a strong opinion on this, but as long as the top bar has buttons to trigger actions, such as night and advanced mode, for me makes sense to always display this topbar even if the user scrolls down

**Comment by dsimog01** [comment]
Yup, that is exactly what I mean, I think the topbar actions should be available even if the user scrolls down
