### ISSUE TITLE
Allow changing the fee recipient to the `Dappnode Smoothing Pool` fee recipient

### ISSUE THREAD

**Issue by dsimog01** [dappnode/StakingBrain#228]
There should be an option in the `edit fee recipient` box that allows the user to subscribe the validators to the SP in two steps:
1. Change the fee recipient to the one of the Dappnode SP
2. Give the user context and information on the 2 possible subscription methods
3. If you want to stay on the "automatic subscription" track, you can close this dialog
4. If you want to go to the "manual subscription" (recommended) track, send the user to the SP website so that they can perform the required tx

**Comment by pablomendezroyo** [comment]
![Screenshot 2023-11-09 at 13 24 05](https://github.com/dappnode/StakingBrain/assets/41727368/8b4d1b8a-5353-453e-a697-786ab9ff71b5)

Add a button to automatic subscribe to MEV smoothing pool. Input empty, button with mev recommended

**Comment by pablomendezroyo** [comment]
Check working progress https://github.com/dappnode/StakingBrain/pull/239

**Comment by pablomendezroyo** [comment]
Done!
