### ISSUE TITLE
Create new tab in the staking brain for smooth: Show validators MEV SP rewards summary

### ISSUE THREAD

**Issue by dsimog01** [dappnode/StakingBrain#230]
We could have a box in the Staking Brain that summarizes the rewards pending or claimable using the Oracle API

**Comment by pablomendezroyo** [comment]
Conclusion: add a new tab fo the smoothing pool "Smooth rewards" to show all these data

**Comment by pablomendezroyo** [comment]
Reference smoothing api https://github.com/dappnode/mev-sp-oracle/tree/main/api

**Comment by pablomendezroyo** [comment]
will not implement
