### ISSUE TITLE
Remove Warning for Gnosis Chain Withdrawals

### ISSUE THREAD

**Issue by mrtdlgc** [dappnode/StakingBrain#264]
Exiting through Web3Signer, people still get the "withdrawals are not enabled for Gnosis Chain" warning. As Shapella upgrade has already taken place and fully exit is possible on Gnosis Chain, that warning should be removed.

**Comment by dappnodedev** [comment]
Nice catch! We will push this

**Comment by dappnodedev** [comment]
This has already been merged, it will be published in next release
