### ISSUE TITLE
Add alert if validator registered in Smooth and fee recipient wrong

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/StakingBrain#278]
Add alert if validator registered in Smooth and fee recipietn wrong. Ideally this situation should never be able to be reachable from the UI

**Comment by pablomendezroyo** [comment]
sounds loable! 

@Marketen there could be added a new daemon to the daemons module that periodically checks the fee recipient validators and if its the sm then send the alert, but it could be a bit overwhelmed to the dappmanager

**Comment by Marketen** [comment]
done in https://github.com/dappnode/StakingBrain/pull/291 and https://github.com/dappnode/StakingBrain/pull/287
