### ISSUE TITLE
Add "Subscription Status" Column to StakingBrain

### ISSUE THREAD

**Issue by Marketen** [dappnode/StakingBrain#281]
A validator can be in 5 possible states:
- Subscribed
- Waiting to be subscribed
- Not subscribed
- Subscribed with wrong fee
- Subscribed but with BLS withdrawal address

A validator with BLS shouldnt be able to change its fee recipient to Smooth. We can check withdrawal address type of a validator:
https://github.com/dappnode/StakingBrain/blob/marc/smooth_integration/packages/common/src/types/customValidators/types.ts#L20
https://github.com/dappnode/StakingBrain/blob/marc/smooth_integration/packages/brain/src/calls/getValidators.ts#L47
![image](https://github.com/dappnode/StakingBrain/assets/36164126/526d4ee4-7cab-4777-96de-26981760b5bc)

**Comment by pablomendezroyo** [comment]
Implemented
