### ISSUE TITLE
Do not let user add LIDO keystore if MEV_BOOST is not installed

### ISSUE THREAD

**Issue by Marketen** [dappnode/StakingBrain#316]
Brain can check via global envs http://my.dappnode/global-envs if MEV_BOOST is installed. 

Since all LIDO Node Operators should be running MEV, do not let users import a keystore with tag LIDO if MEV_BOOST is not installed.

It is responsibility of the Node Operator to keep MEV_BOOST running and use its relays.

**Comment by pablomendezroyo** [comment]
Closed by https://github.com/dappnode/StakingBrain/pull/317
